services:
  - type: web
    name: news-please-rh
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    repo: https://github.com/rowandhashem/news-please-rh
    branch: master
